#!/usr/bin/env bash
# Displays 'Holberton School' 10 times buth 9th iterarion displays  'Hi'
i=0
while [ $i -lt 10 ]; do
    echo "Holberton School"
    if [ $i -eq 8 ]; then
	echo "Hi"
    fi
    let "i++"
done
