#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and print hi in 9 line.
i=0
while [ $i -lt 10 ]
do
    if ((i == 9)); then
        echo "Hi"
    fi
    echo "Holberton School"
    ((i++))
done
