#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
# - Hours from 0 to 12
# - Minutes from 1 to 59
hours=0
mins=1
while [ $hours -lt 13 ];do
    let "mins=1"
    echo "Hour: $hours"
    while [ $mins -lt 60 ]; do
	echo "$mins"
	let "mins++"
    done
    let "hours++"
done
