#!/usr/bin/env bash
# displays:
# - The content of the current directory
# - In a list format
# - Where only the part of the name after the first dash is displayed
my_dir=$(ls)
for files in $my_dir; do
    echo "$files" | cut -d '-' -f2
done
